name: Homebrew

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@503c7f3bf65dfaeed2a1609f9446824e354c3370 # main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@503c7f3bf65dfaeed2a1609f9446824e354c3370 # main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@503c7f3bf65dfaeed2a1609f9446824e354c3370 # main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repomix
